import libs = \
    pugixml%lib{pugixml} \
    libboost-graph%lib{boost_graph} \
    libboost-flyweight%lib{boost_flyweight} \
    libboost-hana%lib{boost_hana} \
    epoxy%lib{epoxy} \
    gtkmm-4.0%lib{gtkmm} \
    Eigen%lib{Eigen}

import testlibs = \
    catch2%lib{catch2} \
    catch2%lib{catch2wmain}

exe{tests}: {hxx h cxx c}{engine/** graphics/**} $libs $testlibs
exe{tests}: test = true
exe{citty}: {hxx h cxx c}{* engine/** graphics/**} $libs

cc.poptions =+ "-I$out_root" "-I$src_root"